import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';
import { notifyApplicationEvent } from '@/lib/notification-hooks';
import type { Lead } from '@/types/database';

interface ConversionResult {
  success: boolean;
  applicationId?: string;
  applicationNumber?: string;
  error?: string;
}

export function useLeadConversion() {
  const { user } = useAuth();
  const [isConverting, setIsConverting] = useState(false);
  
  /**
   * Convert a lead to an application
   * This creates a new application record linked to the lead
   */
  const convertToApplication = async (lead: Lead): Promise<ConversionResult> => {
    if (!user) {
      return { success: false, error: 'User not authenticated' };
    }
    
    setIsConverting(true);
    
    try {
      // Check if application already exists for this lead
      const { data: existingApp } = await supabase
        .from('applications')
        .select('id, application_number')
        .eq('lead_id', lead.id)
        .maybeSingle();
      
      if (existingApp) {
        return { 
          success: true, 
          applicationId: existingApp.id,
          applicationNumber: existingApp.application_number,
        };
      }
      
      // Create new application - application_number is auto-generated by trigger
      const { data: newApp, error } = await supabase
        .from('applications')
        .insert([{
          lead_id: lead.id,
          ro_id: lead.ro_id,
          application_number: 'TEMP', // Will be replaced by trigger
          status: 'submitted',
        }])
        .select()
        .single();
      
      if (error) throw error;
      
      // Update lead status to submitted
      await supabase
        .from('leads')
        .update({ status: 'submitted' })
        .eq('id', lead.id);
      
      // Log workflow history
      await supabase.from('workflow_history').insert([{
        application_id: newApp.id,
        action: 'create',
        from_status: null,
        to_status: 'submitted',
        performed_by: user.id,
        notes: `Application created from lead ${lead.lead_number}`,
      }]);
      
      // Trigger notification
      await notifyApplicationEvent('application_created', {
        application_number: newApp.application_number,
        lead_number: lead.lead_number,
        customer_name: lead.customer_name,
        customer_phone: lead.customer_phone,
        customer_email: lead.customer_email || undefined,
        ro_id: lead.ro_id,
      });
      
      toast.success(`Application ${newApp.application_number} created`);
      
      return {
        success: true,
        applicationId: newApp.id,
        applicationNumber: newApp.application_number,
      };
      
    } catch (error: any) {
      console.error('Error converting lead to application:', error);
      toast.error('Failed to create application');
      return { success: false, error: error.message };
    } finally {
      setIsConverting(false);
    }
  };
  
  /**
   * Batch convert multiple leads to applications
   */
  const batchConvert = async (leads: Lead[]): Promise<{
    successful: ConversionResult[];
    failed: ConversionResult[];
  }> => {
    const results = await Promise.all(leads.map(convertToApplication));
    
    return {
      successful: results.filter(r => r.success),
      failed: results.filter(r => !r.success),
    };
  };
  
  return {
    convertToApplication,
    batchConvert,
    isConverting,
  };
}
